# 这个文件仅用于生成文档，配置项并不完整，可以在<https://github.com/wu-kan/wu-kan.github.io/blob/master/_config.yml>获取完整配置文档及示例！
title: jekyll-theme-WuK
description: A content-first, sliding sidebar theme for Jekyll.
url: https://jekyll-theme-WuK.wu-kan.cn
baseurl: ""
tagline: wu-kan

jekyll-theme-WuK:
  home:
    append_before: |
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/reveal.js/css/reveal.min.css" />
      <style>
      .reveal .slides {
        text-align: left;
      }
      </style>
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/reveal.js/css/theme/serif.min.css" />
      <script defer="defer" src="https://cdn.jsdelivr.net/npm/reveal.js/js/reveal.js" onload="
        document.getElementsByClassName('wrap')[0].classList.add('reveal');
        let path = 'https:\/\/cdn.jsdelivr.net/npm/reveal.js/';
        Reveal.initialize({
          height: '100%',
          hash: true,
          mouseWheel: true,
          navigationMode: 'linear',
          parallaxBackgroundImage: 'data:image/webp;base64,UklGRiQAAABXRUJQVlA4IBgAAAAwAQCdASoBAAEAD8D+JaQAA3AA/uVqAAA=',//这是一张纯白图
          dependencies: [
              // Interpret Markdown in <section> elements
              { src: path+'plugin/markdown/marked.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
              { src: path+'plugin/markdown/markdown.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
      
              // Syntax highlight for <code> elements
              { src: path+'plugin/highlight/highlight.js', async: true },
      
              // Zoom in and out with Alt+click
              { src: path+'plugin/zoom-js/zoom.js', async: true },
      
              // Speaker notes
              { src: path+'plugin/notes/notes.js', async: true },
      
              // MathJax
              { src: path+'plugin/math/math.js', async: true }
          ]
          });
        "></script>
  page:
    masthead:
      enable: true
    append_before:
      - | # 增加宽屏下的显示内容
        <style>
          @media (min-width: 66rem) {
            .container {
              max-width: calc(100vw - 28rem);
            }
          }
        </style>
      - | # 给文章加上白色背景，防止被背景影响阅读
        <style>
          .masthead {
            background-color: rgba(255, 255, 255, 0.9);
            box-shadow: 0 .25rem .5rem rgba(0, 0, 0, 0.1);
          }
          .content {
            background-color: rgba(255, 255, 255, 0.9);
            box-shadow: 0 .25rem .5rem .5rem rgba(255, 255, 255, 0.9);
            border: none;
          }
        </style>
      - | # 加载动画
        <style>
          .masthead,
          .content {
            animation: animationAppear 2s;
          }
          @keyframes animationAppear {
            0%,
            33% {
              opacity: 0;
            }
            100% {}
          }
        </style>
      - | # Katex
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/katex/dist/katex.min.css"
        />
        <script
          src="https://cdn.jsdelivr.net/npm/katex/dist/katex.min.js"
          defer="defer"
        ></script>
        <script
          src="https://cdn.jsdelivr.net/npm/katex/dist/contrib/auto-render.min.js"
          defer="defer"
          onload='renderMathInElement(document.body, { delimiters: [{ left: "$", right: "$", display: false }] })'
        ></script>
        <script
          src="https://cdn.jsdelivr.net/npm/katex/dist/contrib/mathtex-script-type.min.js"
          defer="defer"
        ></script>
  default:
    body:
      theme-base: theme-base-0d
      layout-reverse: false # 开启后sidebar在右边，反之左边
      sidebar-overlay: false # 开启后正文不随sidebar移动而移动
    sidebar:
      avatar: # 侧边栏显示的头像
        enable: true
        img: https://gravatar.loli.net/avatar/a12c5fff23dde00df79af9aca4e7b6e4?s=300 # 头像的地址
      nav:
        - title: '<i class="fas fa-home fa-fw"></i> 我的主页'
          href: https://wu-kan.cn/
        - title: '<i class="fas fa-file-code fa-fw"></i> 这篇文档'
          href: /
      simple_jekyll_search:
        enable: false
        full_text_search: false # 可能导致缓慢的搜索和加载
      append_to_sidebar:
        - | # 目录插件
          <aside id="toc" style="max-height: 50vh;overflow: auto;">
            目录
          </aside>
          <script
            defer='defer'
            src='https://cdn.jsdelivr.net/npm/html-contents/html-contents.min.js'
            onload="htmlContents('#toc', {listType: 'o', filter: function(arr) {return !arr.matches('.masthead-title')}})"
          ></script>
        - | # Copyright
          <div>
            <i class="fas fa-copyright fa-fw"></i>
            2020 WuK
          </div>
        - | # 不蒜子页面统计
          <div>
            <div>
              <i class="fas fa-eye fa-fw"></i>
              <span id="busuanzi_value_page_pv">
                <i class="fas fa-spinner fa-pulse"></i>
              </span>次
            </div>
            <div>
              <i class="fas fa-paw fa-fw"></i>
              <span id="busuanzi_value_site_pv">
                <i class="fas fa-spinner fa-pulse"></i>
              </span>枚
            </div>
            <div>
              <i class="fas fa-user-friends fa-fw"></i>
              <span id="busuanzi_value_site_uv">
                <i class="fas fa-spinner fa-pulse"></i>
              </span>人
            </div>
            <script
              src='https://cdn.jsdelivr.net/npm/busuanzi'
              defer='defer'
            ></script>
          </div>
      wordcount:
        enable: true
        alert: <i class="fas fa-user-edit fa-fw"></i>
        kilo: 千
        unit: 字
    append_to_head: # 通过内嵌html的方式引入并定制插件，删改前确定知道自己在做什么。定制插件的方式可以参考这篇文章<https://wu-kan.cn/_posts/2019-01-18-基于Jekyll搭建个人博客/>
      - |
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0, maximum-scale=1"
        />
        <meta
          http-equiv="content-type"
          content="text/html; charset=utf-8"
        />
        <link
          rel="apple-touch-icon-precomposed"
          href="https://gravatar.loli.net/avatar/a12c5fff23dde00df79af9aca4e7b6e4?s=300"
        />
        <link
          rel="shortcut
          icon"
          href="https://gravatar.loli.net/avatar/a12c5fff23dde00df79af9aca4e7b6e4?s=32"
        />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/gh/poole/lanyon@ac85a3115c094b3e6cb92cc41771e98b443f6c5d/public/css/poole.min.css"
        />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/gh/poole/lanyon@ac85a3115c094b3e6cb92cc41771e98b443f6c5d/public/css/lanyon.min.css"
        />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free/css/all.min.css"
        />
      - | # 网站字体
        <style>
          html,
          h1,
          h2,
          h3,
          h4,
          h5,
          h6,
          .sidebar {
            line-height: normal;
            font-family: Menlo, Monaco, "Courier New", Microsoft JhengHei, monospace;
          }
        </style>
      - | # 网站背景图片，分竖屏、宽屏
        <style>
          .wrap {
            min-height: 100vh;
            display: inline-block;
            background-size: 100vw auto;
            background-position: center top;
            background-repeat: no-repeat;
            background-attachment: fixed;
            background-image: url(/assets/image/74559485_p1.webp);
          }
          @media (min-aspect-ratio: 2400/1850) {
            .wrap {
              background-image: url(/assets/image/71932901_p0.webp);
            }
          }
        </style>
      - | # 头像效果
        <style>
          .effect {
            margin: 1rem;
            perspective: 900px;
          }
          .effect-info {
            text-align: center;
            -webkit-backface-visibility: hidden;
            backface-visibility: hidden;
            position: absolute;
            top: 0;
            transform-style: preserve-3d;
          }
          .effect-img {
            z-index: 11;
            width: 100%;
            height: 100%;
            position: relative;
            transition: all 0.5s ease-in-out;
          }
          .effect-img:before {
            position: absolute;
            display: block;
          }
          .effect-right_to_left .effect-img {
            transform-origin: 0% 50%;
          }
          .effect-right_to_left:hover .effect-img {
            transform: rotate3d(0, 1, 0, -180deg);
          }
        </style>
      - | # 彩虹滚动条，仅对Chrome系浏览器生效
        <style>
          ::-webkit-scrollbar {
            width: 4px;
            height: 4px;
          }
          ::-webkit-scrollbar-thumb {
            background: linear-gradient(-45deg, #ee7752, #e73c7e, #23a6d5, #23d5ab);
          }
        </style>
      - | # 对于原lanyon的一些补丁
        <style>
          pre {
            max-height: 50vh;
            overflow: auto;
            background-color: rgba(0, 0, 0, 0);
          }
          img {
            display: inline-block;
            margin: 0;
          }
          /* Hide the sidebar checkbox that we toggle with `.sidebar-toggle` */
          .sidebar-checkbox {
            display: none;
          }
          .sidebar-toggle {
            position: fixed;
          }
          .sidebar-toggle:before,
          .sidebar-toggle:active:before,
          #sidebar-checkbox:focus~.sidebar-toggle:before,
          #sidebar-checkbox:checked~.sidebar-toggle:before {
            background-image: none;
          }
        </style>

markdown: kramdown
kramdown: # 见https://kramdown.gettalong.org/options.html
  input: GFM # 见http://jekyllcn.com/docs/configuration/#kramdown
  syntax_highlighter_opts: # 可见https://kramdown.gettalong.org/syntax_highlighter/rouge.html
    disable: true # 关掉默认的高亮，换用prismjs

# permalink: /_posts/:year-:month-:day-:title/ #生成文章的地址格式，我希望它和_posts目录下的格式一样
# timezone: Asia/Shanghai # 解决githubpage显示时间不正确的问题，见https://www.iana.org/time-zones
# future: false # 不发布时间在未来的文章

# limit_posts: 999 # 限制博文数量
# encoding: utf-8

# 以下为 githubpage上不可修改的参数，见https://help.github.com/en/github/working-with-github-pages/about-github-pages-and-jekyll
#lsi: false # 为相关文章生成索引
#safe: true # 禁用自定义插件
#source: [your repo's top level directory] # Jekyll 读取文件的路径
#incremental: false # 增量生成
#highlighter: rouge # 代码高亮器
#gist:
#  noscript: false
#kramdown:
#  math_engine: mathjax
#  syntax_highlighter: rouge

plugins: # https://jekyllrb.com/docs/plugins/ githubpage上支持的插件见https://pages.github.com/versions/
  - jekyll-readme-index
  - jekyll-default-layout
  - jekyll-seo-tag

readme_index:
  with_frontmatter: true
